### ISSUE TITLE
请求

### ISSUE THREAD

**Issue by yemoyu123** [torikushiii/BlueArchiveData#1]
请问一下佬能不能整个proto，想试试看整个私服
![QQ截图20230817163502](https://github.com/torikushiii/BlueArchiveData/assets/88332986/292cbe5b-c221-42e9-b6b3-71a4c19e0f03)
![QQ截图20230817163547](https://github.com/torikushiii/BlueArchiveData/assets/88332986/1b7bc82a-8364-437b-b6b7-83efc3e45dbf)

**Comment by torikushiii** [comment]
抱歉，但我没有提取任何proto文件，但也许将来如果我找到一种方法，我会将其发布在这个存储库上

**Comment by yemoyu123** [comment]
> 抱歉，但我没有提取任何proto文件，但也许将来如果我找到一种方法，我会将其发布在这个存储库上

非常感谢！我期待那一天
